[package]
name = "bgf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.45.0"
glad-gl = { path = "../glad-gl" }
stb = "0.3.2"
rand = "0.8.5"
